### ISSUE TITLE
Disabling TP per world

### ISSUE THREAD

**Issue by xBlueXFoxx** [Multiverse/Multiverse-Portals#105]
There should be the option to prevent any means of accessing the world except for portal access.

For example: My server the world1 has /tp to teleport to players, but it also works teleporting from world1 to world2, when I only want it to where the only access to world2 would be through the world portal.

**Comment by FernFerret** [comment]
This issue really doesn't belong in portals, since you'd like other plugins to obey the rules too. Not sure exactly what you're after. If you're still interested, read below.

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
