### ISSUE TITLE
Severe Errors in console

### ISSUE THREAD

**Issue by halorrr** [Multiverse/Multiverse-Portals#107]
If i have just Multiverse Core install my server works perfectly fine but after i install multiverse portals it causes problems. The server loads up fine but if a create a world this happens:
http://pastebin.com/w52bGxfQ
A bunch of errors appear then the server lags out for any players connected though the server thinks they are still connected, how can I fix this, i'd like to have multiverse portals but i can't have it on if it does this.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
