### ISSUE TITLE
World Access Game Mode Glitch

### ISSUE THREAD

**Issue by st392** [Multiverse/Multiverse-Portals#108]
I do not give access to the creative world to new players.  I do this by not giving them the multiverse.access.Creative_World permission through GroupManager.  When those players stand in the portal that is linked to Creative World, they are not grant access to the creative world, but it still puts those players in creative mode in the survival world.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
