### ISSUE TITLE
Your plugin is causing huge lagg.

### ISSUE THREAD

**Issue by WoAnerges** [Multiverse/Multiverse-Portals#110]
Multiverse-Portals v2.3-b484
    PlayerMoveEvent Time: 40021217000 Count: 4479258 Avg: 8934
    PlayerTeleportEvent Time: 318558000 Count: 4647 Avg: 68551
    PlayerInteractEvent Time: 857362000 Count: 115247 Avg: 7439
    PluginEnableEvent Time: 90000 Count: 8 Avg: 11250
    BlockPhysicsEvent Time: 76836729000 Count: 56783385 Avg: 1353
    PlayerPortalEvent Time: 10426000 Count: 112 Avg: 93089
    PlayerBucketFillEvent Time: 7907000 Count: 73 Avg: 108315
    PlayerBucketEmptyEvent Time: 17926000 Count: 173 Avg: 103618
    BlockFromToEvent Time: 77075278000 Count: 2517485 Avg: 30615
    VehicleMoveEvent Time: 44511780000 Count: 38592919 Avg: 1153
    MVPlayerTouchedPortalEvent Time: 264058000 Count: 7790 Avg: 33897
    Total time 239921331000 (239s)

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
