### ISSUE TITLE
You need to LEFT click on a block with your wand!

### ISSUE THREAD

**Issue by Takomari** [Multiverse/Multiverse-Portals#117]
Hello,
I'm using WorldEdit and worldGuard and have been running Multiverse Core and Portals perfectly until now.
I keep being told: "You need to LEFT click on a block with your wand!" every time I try to create a portal.

Any help? This is the only information  I have about it.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).

**Comment by Rituvl** [comment]
1.14.2 still the same issue. Please fix

**Comment by dumptruckman** [comment]
@Rituvl If you're still experiencing this issue, please open a new ticket after reading https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug.
