### ISSUE TITLE
Invalid destination

### ISSUE THREAD

**Issue by dawgflymd** [Multiverse/Multiverse-Portals#122]
Installed:
craftbukkit-1.1-R3 AND 1.1-R4
Multiverse 2.3 AB
Multiverse Portals

When I go to set a portal, I can successfully create one however the destination is never recorded. It always shows up in the console as "Portal namehere has an invalid DESTINATION!" 

If I look in the .yml, it does not show any destination set. If I manually add one in and reload, the console--yet again-- screams that there is no portal destination set for any portal, and the .yml is set as Invalid Destination in the dest field.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
