### ISSUE TITLE
Nether portals dont work

### ISSUE THREAD

**Issue by c4ddy** [Multiverse/Multiverse-Portals#136]
I am assuming it is a issue with multiverse portals.

when you create a nether portal with obsidian it fills and and looks like it should but when you get it you dont go anywhere?

I am using:
bukkit 1.1-r6-33
multiverse 2.4-b516
multiverse-portals 2.4-b524
residence 
lockette

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
