### ISSUE TITLE
Enderportals don't work as excepted

### ISSUE THREAD

**Issue by julianschuh** [Multiverse/Multiverse-Portals#159]
Hello,

I think (I'm not 100% sure about that) that enderportals dont work as they are supposed to.

When entering a Enderportal in a stronghold in the world (e.g. at Coordinates 500, 30, -500) the enderportal will teleport the player to exact that location (500, 30, -500) in the end (A obisidian Platform will spawn below the player). This is a huge problem, because the most players won't have ressources (and orientation) to build a ~1000 blocks bridge to the end, which is always located at 0, 0.
When changing the the scale factor of the end, the player spawns at another location.

In my opinion the player should always spawn at the ends spawn point when entering a enderportal - the spawn location should not depend on the portal which is entered.

I'm not sure how this works with a Vanilla Server, but i think its wrong that the player just spawns at a portal dependent location in the end.

Thanks in Advance!

Regards
julezjulian

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
