### ISSUE TITLE
Players are unable to use portals.

### ISSUE THREAD

**Issue by blackreaperhei** [Multiverse/Multiverse-Portals#166]
I recently installed this plugin and have created a few portals. I have tested them and they work, however, whenever regular players attempt to use them, nothing happens.

I have checked my PermissionsEx permissions.yml file and they have the correct permissions.
Could you please tell me what the problem is? Thank you.

Also, here is a pastebin of my permissions.yml:
http://pastebin.com/3vNq5YJG

Just in case, I have included a copy of the actual file:
http://localhostr.com/dJyXwkPWiwLQ

My config file for Multiverse Core:
http://localhostr.com/9yDEca2MrjfM

My config file for Multiverse Portals as well as the 'portals.yml' file:
http://localhostr.com/Fcg2Sxd4OJei
http://localhostr.com/4mbT99O6RYjz

Thanks again.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
