### ISSUE TITLE
Portals do not work at all

### ISSUE THREAD

**Issue by saedric** [Multiverse/Multiverse-Portals#170]
I am running craftbukkit 1.2.5-R2.0. I have Multiverse-Core and Multiverse-Inventories. Neither me, the server owner, nor my players can use portals. I have enfore-access: false. Any help?

EDIT: We can't use nether or the end portals.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
