### ISSUE TITLE
Portals dont work for other players

### ISSUE THREAD

**Issue by robotnikthingy** [Multiverse/Multiverse-Portals#178]
hi, i cant get my portals to work for other players. i want to make it so that everyone can use them.

the debug gives the error "MV-Portals is DENYING Player 'ItsoverKaiba' access to use the portal"

here is what my permissionsbukkit config file looks like

```
users:
  
08mstelter:
    
groups:
    - Regulars
  
itsoverkaiba:
    
groups:
    - Regulars
  
CorvetteKingIA:
    
groups:
    - Regulars
  
robotnikthingy:
    groups:
    - Administrators


groups:
  

Default:
    
permissions:
      
permissions.build: false
 

Regulars:
    
permissions:

multiverse.portal.access.*: true
permissions.build: true
 
inheritance:
    - Default
 
 
Moderators:
    
inheritance:
    - Regulars
  
Administrators:
    
permissions:
      
superpermbridge.*: true
    
inheritance:
    - Moderators
```

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
