### ISSUE TITLE
Issues when using Multiverse-Portals and Multiverse-NetherPortals

### ISSUE THREAD

**Issue by Antagonym** [Multiverse/Multiverse-Portals#179]
When using Mutliverse-Portals and Multiverse-NetherPortals together on a server, portals (created with Multiverse-Portals) with the wobbly purple nether texture in them won't work in worlds where no Nether is specified to the Multiverse-NetherPortals plugin, saying "This portal has no valid destination".
(This one is a minor problem in my opinion)

Also those portals (with this purple nether texture created with Multiverse-Portals) are percieved as nether portals. Therefore when building them near a real nether portal they are percieved as possible destinations when transporting back to the normal world. Thus when spawning the player is almost imediately teleported to the destination of this portal (created with Multiverse-Portals).
(I find this one quite annoying)

Both issues do not occure when portals are filles with water or are empty.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

I think your issue may actually be a thing, so please do reopen this with more details

~~This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great!~~

Again, I'm modifying my stuff, because I think I've seen this. I do want more info from you if you're still running a minecraft server and still using Multiverse!

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).

**Comment by FernFerret** [comment]
Closing as inactive (> 7 days without comment from submitter) and we're trying to keep up with idle issues better.

If you're still having issues, please post an update and we'll reopen this!  :+1:
