### ISSUE TITLE
Feature Suggestion: "/mvp createdest" command

### ISSUE THREAD

**Issue by NixillUmbreon** [Multiverse/Multiverse-Portals#186]
If you have a selected portal that has no destination, "/mvp createdest" creates a portal and automatically sets it as the selected portal's destination. Syntax is the same as "/mvp create".

**Comment by FernFerret** [comment]
You can accomplish what you want (with a little more work) via `/mvpm dest XYZ`. I think we have quite enough aliases for the /mvpm commands :) don't you?

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

I don't think we'll be implementing this now, but thank you for the suggestion! I'm closing this issue because it is outside the scope of what we want to do in Multiverse-Portals.
