### ISSUE TITLE
Portal block protection?

### ISSUE THREAD

**Issue by Xavura** [Multiverse/Multiverse-Portals#190]
Do I need to use a separate plugin to protect (block protection) portals?

**Comment by FernFerret** [comment]
Yes. I used to use WorldEdit.

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
