### ISSUE TITLE
Multiverse-Portals 'Cannon' Destination Bug

### ISSUE THREAD

**Issue by samebertz** [Multiverse/Multiverse-Portals#191]
The pitch and yaw coordinates correctly set the angle of the players trajectory, however the viewing angle of the player is always set to look almost straight down. This may not be a bug, but you should either be able to set the angle of the camera, or have it match the pitch and yaw of the launch trajectory.

**Comment by FernFerret** [comment]
Not sure what you mean by this. The idean of the `cannon-2` type destination is that you'd look where you wanted the cannon to fire you. Also, it's kinda a fun test thing I put in there :)

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
