### ISSUE TITLE
Portal Issue

### ISSUE THREAD

**Issue by SpoiledCow** [Multiverse/Multiverse-Portals#192]
So, I have world 1 and world 2. I set up a 4x5 portal in world 1 and world 2. First, I drag the corners of the portal and /mvp create Portal1. I go to world2 where Portal2 is, and /mvp create Portal2. Then I did /mvp modify dest p:Portal1. I walk into the portal, and sure it works. Then I did /mvp select Portal1. Next, I did /mvp modify dest p:Portal2. I walk over it, but it doesnt Tp me.

How do I fix?

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
