### ISSUE TITLE
Destination setting

### ISSUE THREAD

**Issue by scopulus** [Multiverse/Multiverse-Portals#199]
So MV2 Portals worked wonders up until I need it the most now. I'm simply trying to link to set portals together and this is the error I ALWAYS get when trying to do so:

"Property dest of portal <PORTAL1> was not set to <PORTAL2>
Multiverse could not find the destination: <PORTAL1>"

What gives. This is very. VERY frustrating.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
