### ISSUE TITLE
Teleports to the End when Walking Through a Portal from a Corner Block

### ISSUE THREAD

**Issue by Suffice** [Multiverse/Multiverse-Portals#204]
If a portal is created without a frame, it becomes invisible, thereby having a more magical and less nether portal feel to it, and it works just fine, so long as you don't walk into it from nonadjacent diagonal position, which then will teleport one to the End instead of the destination.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
