### ISSUE TITLE
useonmove: false is very important to be repaired in 1.4.2

### ISSUE THREAD

**Issue by drdeft** [Multiverse/Multiverse-Portals#205]
We have configured **useonmove: false** on our servers. This feature is very important. Dear developer, please repair it in 1.4.2. With online over 70 **useonmove: true** makes huge lags.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
