### ISSUE TITLE
filled portals doesn't port rightly

### ISSUE THREAD

**Issue by Telbaru** [Multiverse/Multiverse-Portals#212]
Hey,
Every Portal that is filled with water ore lava/netherportals doesn't port the player rightly. If you go through the portal A and move instantly out of the Portal B the player will be teleported to the Portal A. So you must stand 2-3 Seconds in portal B to leave it rightly. Please fix this.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
