### ISSUE TITLE
Portals not working right

### ISSUE THREAD

**Issue by jdneese96** [Multiverse/Multiverse-Portals#216]
Hi, I setup a pair of portals. When I go into a portal, it takes me to the destination b (to the other portal which you can go into that portal to get to portal a) and then back to a. I'm not sure what I should do. I have erased the mvp folder and re spawned my config, and I get the same thing. 
If you can help, I'd appreciate it. Thanks.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
