### ISSUE TITLE
Extremely slow loading of portals on startup

### ISSUE THREAD

**Issue by frekky** [Multiverse/Multiverse-Portals#217]
I own a private server that uses Multiverse for world management and portals. I have set up 89 portals going to various places in different worlds and it takes up to 120 seconds to load.
Generally I start the server up on a regular basis and if a plugin takes too long to load it is really a problem. Here is an example from the server log:
16:47:39 [INFO] [Multiverse-Portals] - Version 2.5-b659 Enabled - By Rigby and fernferret
16:49:39 [INFO] [MVPLogging] 89 - Portals(s) loaded

**Comment by FernFerret** [comment]
I know @main-- has made multiple efficiency fixes since this ticket.

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
