### ISSUE TITLE
Portal Not Changing Gamemode For Some Players

### ISSUE THREAD

**Issue by Chrisski3** [Multiverse/Multiverse-Portals#220]
When a player will telport to another world their game-mode stays the same. 
For example: Player from a creative world goes to a survival world by walking through a teleporter. Their game-mode will still be Creative when it should be Survival.

**Comment by FernFerret** [comment]
You sure they don't have the ignore permission? https://github.com/Multiverse/Multiverse-Core/blob/601f457e6f976d1884be1f216b11ebbfd49043eb/src/main/java/com/onarandombox/MultiverseCore/MVWorld.java#L380

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
