### ISSUE TITLE
Permissions Problem

### ISSUE THREAD

**Issue by SebixDDD** [Multiverse/Multiverse-Portals#221]
Hi,
first I have to say that mvp is a great plugin, but how can I disable the permsissions?
Why isn`t there a point in the config file, where I can make, that I needn't make for every portal a permission.
Can you help me?

Sincerly,
Sebi

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
