### ISSUE TITLE
Portal doesnt teleport vehicles

### ISSUE THREAD

**Issue by MrInfro** [Multiverse/Multiverse-Portals#226]
The portal doesnt teleport minecarts when passing through

**Comment by FernFerret** [comment]
No idea what the commit was due to the DCMA takedown :(

Probably related to https://github.com/Multiverse/Multiverse-Portals/issues/267

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
