### ISSUE TITLE
Portals non functional in build 670

### ISSUE THREAD

**Issue by trackhed** [Multiverse/Multiverse-Portals#228]
Upgrading to CB 1.4.6 R0.3 I installed and tested all latest development builds for Multiverse plugins. All are working correctly, except I couldn't get portals to actually teleport. When constructing the portal I would get the same WEAPI return in the console, I'm assuming meaning that the world edit API hook was called correctly. Entering the portal does not actually teleport to any destination though.
I fixed the issue by downgrading to the AB

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
