### ISSUE TITLE
Ridiculously long load times upon startup with medium-large number of portals and long time upon creation of new portals

### ISSUE THREAD

**Issue by remiscarlet** [Multiverse/Multiverse-Portals#236]
I currently have 40 portals enabled, but the average time it takes for the server to get through loading MV-portals is approximately ~7 minutes. I'm not entirely sure if something similar to https://github.com/Multiverse/Multiverse-Portals/issues/129 is occurring again, but an average load time of ten(10) seconds per portal seems pretty ridiculous. 

I would imagine the cause is from the same issue as the loadtime, but creating new portals also takes a really long time where the server will get stuck on the process for anywhere from 5 to 15 seconds. Users are generally disconnected during this wait period. As far as how I know MVP is causing the issue, NoLagg reports a stuck thread originating from MVP.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
