### ISSUE TITLE
PlayerTeleportEvent - Major Lag

### ISSUE THREAD

**Issue by ZxGuNneRocKz** [Multiverse/Multiverse-Portals#238]
I ran a nolagg report to find multiverse-portals causing major lag, as you can see here.

http://prntscr.com/uoatt
http://prntscr.com/uoaut

CB: it-Bukkit-1.4.7-R0.1-b2602jnks (MC: 1.4.7) (Implementing API version 1.4.7-R0.1)
Latest MV-Portals RB Build.

Plugin Timings: http://pastebin.com/tbf2L4SZ

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
