### ISSUE TITLE
Economy Exemption not working.

### ISSUE THREAD

**Issue by Kainzo** [Multiverse/Multiverse-Portals#242]
Looks like the exemption cost isnt working for Portals
My tester has op / all multiverse commands and it still charges for using a portal that has a set cost/price.
I just tested granting the actual portal name to my permission group.
"multiverse.portal.exempt.test2000 and .all" - still charged for the portal-use when I went through test2000 portal.

The overall goal here is to allow VIP users to be exempt from the charge while default users are forced to pay.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).

**Comment by Kainzo** [comment]
Thanks Fern - it was fixed, I had one of the devs resolved the issue years ago :)
