### ISSUE TITLE
multiverse.portal.access.portalname doesn't work with the latest dev build

### ISSUE THREAD

**Issue by rnoa** [Multiverse/Multiverse-Portals#263]
Only the permission to all portals multiverse.portal.access.* works after updating multiverse core, portals, inventories and nether portals to the newest dev builds. I have spent the whole day trying to figure out why players suddenly could not use the portals and giving them permission to all portals was the only solution, but this is not what I want... Please help! Is this a bug or have I missed something about the newest multiverse builds?

**Comment by FernFerret** [comment]
Have you tried seeing what the debug output from `/mv debug 3` states?

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
