### ISSUE TITLE
Nether portal issue.

### ISSUE THREAD

**Issue by Caamflyer** [Multiverse/Multiverse-Portals#264]
I have created a world and have mv portals hocked up to it. When ever I try to create a regular nether portal it will not take them to the nether. Do I need mvnp to help my problem?

**Comment by FernFerret** [comment]
It's probably a world access issue, use `/mv debug 3` to enable debug output. Reopen this issue if you still have issues.

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
