### ISSUE TITLE
Portals Teleport Sideways

### ISSUE THREAD

**Issue by nrubin29** [Multiverse/Multiverse-Portals#266]
Whenever I teleport through a portal, I come out facing the portal wall.

**Comment by FernFerret** [comment]
You can set the direction by specifying `:ne` for northeast. See [this page for more info](https://github.com/Multiverse/Multiverse-Core/wiki/Destinations#portal-destinations---requires-multiverse-portals).

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
