### ISSUE TITLE
Multiverse doesn't generate a PlotMe terrain

### ISSUE THREAD

**Issue by Braydo99** [Multiverse/Multiverse-Portals#269]
I am trying to make part of my server a creative server, using the PlotMe plugin. I used the following command for 1.4.7 Multiverse-
/mv create creative normal -g PlotMe

When I teleport to the world, I get a normal terrain. Is this a problem with multiverse or Plotme? I use a modded client and server, and if it helps, I get it from http://www.technicpack.net/modpack/details/millenaire-elite.95098. Thanks!

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
