### ISSUE TITLE
Run commands passing through portals

### ISSUE THREAD

**Issue by gorbb** [Multiverse/Multiverse-Portals#272]
Hello Multiverse team,

I'd like to humbly request a new addition to Multiverse-Portals that would run a command when a player passes through a portal.

For example, running a Skyblock plugin allows access to a player's Skyblock via running a command, such as /island.
However, using Multiverse-Portals, I'd like it if said command could be processed by the player if they pass through the portal.

Example command could be /mvp create SkyWorld c:island

Thanks for reading.

**Comment by FernFerret** [comment]
We'll be looking at better ways of interfacing with command blocks, but I'm not sure what you're saying other than that.

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great!

**Comment by dumptruckman** [comment]
If you know javascript you can add scripts to portals that should be able to do what you're asking

**Comment by level42ca** [comment]
I don't understand why this was closed ...

The OP is very descriptive.

OP wants a feature that will execute a user command when entering a portal

Most (if not all) SkyBlock minigame plugins require the user to type /island to enter their private island.

The OP wants this command to execute when a user enters a portal, as opposed to having to type it in manually each time.

**Comment by dumptruckman** [comment]
What OP wants is already possible using the scripting engine we include with MV. They can set the handlerScript property of a portal to the name of a javascript file that contains the code they want to execute on portal.

**Comment by gorbb** [comment]
I thought I was descriptive enough at the time of posting - although I obviously knew what I was after. It could be that if sorting a lot of tickets, the wrong message was typed, or perhaps that there _did_ need to be more information provided and the person looking wasn't sure what I was after. It's easy to misread something, after all.

But - that doesn't really matter anymore. Whilst I no longer have that specific use case for requiring commands to be run, it appears there was a solution for what I was after, though perhaps one I wasn't aware of.

Is there any online documentation available to help me get up to speed with that? I can't see anything relevant on the wiki or BukkitDev/Spigot pages.

Thanks.

**Comment by level42ca** [comment]
@dumptruckman, I've been trying to figure this out myself for the last few hours. I was able to get my MVP to run a script (Only if the portal had a destination I might add) but I can't seem to get it to run any commands from any other plugins. I did make a post here: https://dev.bukkit.org/projects/buscript/pages/global-functions-and-variables but I figure I should bring the issue here as well.

I can't seem to figure out how to add any other plugin commands to a script. Is there any detailed documentation on this?

**Comment by dumptruckman** [comment]
@level42ca I responded there just now.

**Comment by level42ca** [comment]
@dumptruckman Hey, thanks, so your suggestion did work (Though I needed the "island go" command)

However, my new issue is I can't run the scrip unless there is a destination on the portal. The problem now is, I teleport to the Island, then right back to my destination.

If I remove the destination, then the script will not execute.
