### ISSUE TITLE
Obsidian caused by fill

### ISSUE THREAD

**Issue by KingJulian13** [Multiverse/Multiverse-Portals#280]
Problem: The User can fill the portals with lava & water and create obsidian which blocks the portals.

The User have the permission: multiverse.portal.access.*
[Because i dont want to add every portal, logic?]
And i took them the permission: multiverse.portal.fill.*

So why can they still fill them? Dafuq?

Hope for an answer, KingJulian13

**Comment by FernFerret** [comment]
This is not something that Multiverse does or should do, check out a world protection plugin to manage things like this, example: WorldEdit.

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
