### ISSUE TITLE
Water and Lava flow out of a Multiverse Portal 

### ISSUE THREAD

**Issue by Pepperx3** [Multiverse/Multiverse-Portals#285]
I set up the portal and usually I just place water and it goes just fine but now the water and lava overflow but the portal block works just fine also when you remove a portal it seems to ignore the config and still take you to the nether but I probably set it up wrong for that issue

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
