### ISSUE TITLE
My Multiverse-Portals plugin doesn´t load.

### ISSUE THREAD

**Issue by datsnow** [Multiverse/Multiverse-Portals#286]
Hi, guys.

I am creating a 1.2.5 tekkit classic server, and i was thinking on using MultiVerse-Portals.

I just download it, drag it out on "plugins" folder, and started the server.

When i got in-game, the plugin is not recognized.

Help?

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
