### ISSUE TITLE
portal to portal not working even after setting destination [SOLVED]

### ISSUE THREAD

**Issue by SlenderBro100** [Multiverse/Multiverse-Portals#288]
I have made to portals linking them to each other so they go through. one side works, the other doesn't. I am an op on the server, i've added the permission to the ranks, and they can't get through the portal.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
