### ISSUE TITLE
Multiverse Portals is very slow

### ISSUE THREAD

**Issue by Nicklander** [Multiverse/Multiverse-Portals#289]
Using: Multiverse-Portals v2.5-b696
Multiverse-NetherPortals v2.5-b665
Multiverse-Core v2.5-b670

147 - Portals(s) loaded
Bukkit: 1.6.4 R2.0 b2918

The Portals are loaded very slowly during the startup. It also takes very slow to execute MVP Commands. All the other plugins work fine (also MV-Core and NP)

Please Fix this !

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).

**Comment by real2two** [comment]
^ same things happened to me... it is sometimes really slow

**Comment by benwoo1110** [comment]
Can you provide with more details? Like the version of mv you are using. It is possibility due to you not using the latest, or your server version does not allow for it.
