### ISSUE TITLE
Portals not linking:/

### ISSUE THREAD

**Issue by Evilape2698** [Multiverse/Multiverse-Portals#290]
hello there,
 when i try to like my 2 portals, i get this error
![2013-12-03_10 36 13](https://f.cloud.github.com/assets/6090731/1660104/f0332dec-5bb3-11e3-9e5f-398a2a517c49.png)

pls contact me on: m.hummer1998@gmail.com

**Comment by FernFerret** [comment]
You need to use the command like this:

`/mvpm dest w:world -p myPortal`

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
