### ISSUE TITLE
Server Crash when riding through Portals sitting in a Minecart (both for destinations: w:[worldname] and p:[portalname])

### ISSUE THREAD

**Issue by Moorleiche2k** [Multiverse/Multiverse-Portals#294]
As title says. The Portals connect Portals between different worlds. Both the AB as well as the latest dev builds crash the server.
The crash occurs not necessarily right after the first port, it might work 2-3 times. 
If the server crashes, the player, who is sitting in the minecart, gets a blue sky as if the world is not loading. The rest of the players can't build anymore / do anything and after ~10 seconds you loose the connection (server crash).
Also optically one leaves a portal riding half in the block below the portal (not quite sure if this is related o the crash).

Update:

Tested with:
- bukkit v.1.7.2-R2.0 (beta-build)
- bukkit v.1.6.4-R2.0 (recommended build)
- several of the more recent dev-versions of multiverse-core and also multiverse-portals. Also each of the latest AB-versions were tested
- as destinations both w:[Worldname] and p:[portalname]:[facingdirection], the options "safeteleport" and "teleportnonplayers", falling through (vertical movement) a portal instead of "driving" (horizontal movement) through a portal, different portals sizes as well as leaving a few blocks of air beneath the portals were tested

1. Crash occured NEVER the first time after you have gone through a portal but mostly at the 2nd or 3rd time, e.g. if you are going back in that minecart to the other world. Its portal-independent; in other words you may have 4 portals - 2 departure and 2 arrival portals. One of each pair at the same world. Using the first pair of departure and arrival portals teleports you fine, going back through the other pair mostly crash the game. No difference if you use 2 portals linking at each other.

2. Keeping the chunks active does not help: We tested it with players waiting in the chunks (= keeping the chunks active) that contain the portals on the corresponding worlds.

3. For a rare reason it worked once (out of >20 attempts) for several ports between worlds. Not sure why. Then i left and another player joined and the server crashed. We toyed around with safeteleport and teleportnonvehicle-options in the portals.yml at that time.

I once more request a clue or some info about the issue since we have a complex train-station plan and we would like to design the main-spawnworld accordingly to the functions the plugins provide. So if there will/ can be a fix or if this feature won't be available soon please tell. In that case we have to revamp the plan.

**Comment by FernFerret** [comment]
Thanks for the report @Favorlock, marking as resolved. If you feel it's not @Moorleiche2k, see below and reopen.

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
