### ISSUE TITLE
Conflict between Multiverse-Portals and Multiverse-NetherPortals

### ISSUE THREAD

**Issue by Razoul05** [Multiverse/Multiverse-Portals#300]
I am using the following Multiverse Plugins:
- Multiverse-Core
- Multiverse-Inventories
- Mutiverse-Portals
- Multiverse-NetherPortals (recently added).

I have the following Worlds:
- world
- world_nether
- world_the_end
- world_ov17
- world_ov17_nether
- world_ov17_the_end
- world_resource
- world_creative

I had a number of portals defined each linking to a destination portal which were all working as expected. I recently added Multiverse-NetherPortals so I can have a Per-World nether with custom scaling (1:4 ratio rather than 1:8). 

The Nether Portals work fine for each of the worlds that have a nether defined. Any worlds like the Resource world which does NOT have a nether I get the message "This portal goes nowhere!" which is to be expected.

The problem I am experiencing is that my Multiverse-Portals portal in the resource world also reports the message "This portal goes nowhere!" even though it is linked to a portal in another world. In an attempt to determine why this issue is occuring I set Multiverse-Core at log level 3 and enabled the debug mode for Multiverse-Portals (mvp debug on). With debug mode enabled I don't see any errors in my console or log files but instead the portal WORKS AS DESIRED. 

I also found that once I attach a Nether to my resource world any non-nether portals will once again work returning me to their linked destination.

The log file below shows the debug data dumped to the console for 3 event.
1. Moving from world_ov17 to world_resource through a portal (works as expected).
2. Moving from world_resource to world_ov17 through a portal (fails).
3. Moving from world_resource to world_ov17 through a portal with MVP DEBUG ON (works).

http://pastebin.com/rwPkVeP5

**Comment by FernFerret** [comment]
I'll be looking at this one myself, just don't have the time right now, but here's my generic message:

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).

**Comment by Tabinol** [comment]
Same problem reported here with Multiverse-Portal 2.5 and Spigot 1.11.

"/mv reload" works has a work around.
