### ISSUE TITLE
This portal doesn't go anywhere. You should exit it now.

### ISSUE THREAD

**Issue by MrTurboTrio** [Multiverse/Multiverse-Portals#307]
I am pretty sure I have setup the portals correctly. When I walk through a portal, it teleports me to the place I set the destination to, all works perfectly.
Though, when I 'arrive' at the destination, it gives me a message saying 'This portal doesn't go anywhere. You should exit it now.'
http://prntscr.com/34zwzn

What should I do?

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
