### ISSUE TITLE
Portals

### ISSUE THREAD

**Issue by Victhetiger** [Multiverse/Multiverse-Portals#318]
Hi

Theres a Bug When I make a Portal With Portal Blocks (Nether Ones)... When The World as a Nether it tps you in the right place and then it tps you to the nether of the world :/

But if the player reloags.. its fished but still its weird :/

Thanks

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
