### ISSUE TITLE
Nether portals in the portal!

### ISSUE THREAD

**Issue by tryy3** [Multiverse/Multiverse-Portals#319]
Hi, I think this is a bug but I am not 100 sure!

My portals are set up to teleport to a different location.
So portal1 teleports just a few blocks away from portal2 same with the porta2, a few blocks away from portal1.
They both have nether portal blocks in them.

But when I use them they teleport me to the nether.

Steps to reproduce:
1. Create a portal!
2. Use fire to lit the portal to look like a nether portal.
3. Go into the portal.
4. The portal will take you to the destination.
5. It will teleport you to the nether almost immediately.
6. Go out from the nether portal and back in and it will teleport you back to the main world almost immediately.

I tested to remove the nether portal and use water instead, and the portal worked so its just when you fill the portal with nether portals.

Multiverse-Core worlds.yml = http://pastebin.com/Dkwh1M9Y
Multiverse-Core config.yml = http://pastebin.com/9VckqCnh

Multiverse-Portals config.yml = http://pastebin.com/4k3uKc7V
Multiverse-Portals portals.yml = http://pastebin.com/aknJqxcp

Plugin list = http://pastebin.com/V43Aq2EM

Multiverse-Portals version 2.5-b710
Multiverse-Inventories version 2.5-b357
Multiverse-Core version 2.5-b678
CraftBukkit version git-Spigot-1431 (MC: 1.7.8) (Implementing API version 1.7.8-R0.1-SNAPSHOT)

**Comment by FernFerret** [comment]
I tested this today when checking out #374 and my nether-like portals worked great. Please add some additional clarification.

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
