### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by takato1234** [Multiverse/Multiverse-Portals#320]
Hi i have a server and everyone can do tp so i removed the groupmanager and they still can, i downloaded groupmanager and premissionsex at same time maby that and how do i fix please help very fast!!

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
