### ISSUE TITLE
Crash with MultiversePortals errors

### ISSUE THREAD

**Issue by Plumeex** [Multiverse/Multiverse-Portals#321]
Hi, I'm using the latest Multiverse Suite (build 689) with Adventure, Core, NetherPortals, Portals and SignPortals.

This is happening 1-2 times a day: https://pste.me/#/mPW1f (I left the last 2 lines at the top).
I saw
```
com.onarandombox.MultiverseNetherPortals.listeners.MVNPPlayerListener.onPlayerPortal(MVNPPlayerListener.java:109)
```
in the server thread dump, so I thought MultiversePortals might be the culprit.
Could this be a corrupted world/portal?

Thank you. c:

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
