### ISSUE TITLE
V2.5-b699 - Cannot put periods in portal names

### ISSUE THREAD

**Issue by YourHuckleberry** [Multiverse/Multiverse-Portals#328]
Maybe I've been doing a little too much OO lately, but it seemed like a good naming convention at the time.

Regardless - it allows the creation of the portal, and it even works - until the server shuts down, and then it malforms the portals.yml xyz coordinates busting all portals with periods in their names on startup.

```
[MVPLogging] Failed Parsing Location for: alpha (Format Error, was expecting: `X,Y,Z:X,Y,Z`, but got: ``)`
[MVPLogging] Portal alpha has an invalid LOCATION!
[MVPLogging] Portal 'alpha' not loaded due to invalid location!
```

**Comment by FernFerret** [comment]
What did you name the portal? How did you create it?

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
