### ISSUE TITLE
Reloading the plugin causes a long server hang-up

### ISSUE THREAD

**Issue by enforcer574** [Multiverse/Multiverse-Portals#330]
Normally this isn't a problem because I never use /reload, but one of my other plugins (Multiverse-Adventure) feels the need to reload MV-Portals for whatever reason every time it resets an Adventure world on my server. The subsequent reload of MV-portals causes the entire server to hang for several minutes, and disconnects everyone in the process. I have a ton of worlds (just over 30)- could that be the problem?

Using MV-portals b2.5 on Bukkit 1.7.9-R0.1 with 6 GB of RAM allocated to the server

**Comment by dumptruckman** [comment]
Try the latest dev builds at http://ci.onarandombox.com and let us know if you're still experiencing this issue.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
