### ISSUE TITLE
Players warping/tping in

### ISSUE THREAD

**Issue by Vidsify** [Multiverse/Multiverse-Portals#331]
We have a huge problem on our creative server. We have 2 donor world, one double the size plots and the other a normal MC world.

We have given our donors the ability to go through the portals so non donors can't. Is there a way we can stop non donors from using warps set in there and tping to other players inside the world. We also use plotme to create our plots

Thanks in advanced

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
