### ISSUE TITLE
IC2 or TE compable Portal designs

### ISSUE THREAD

**Issue by mudgw2** [Multiverse/Multiverse-Portals#338]
I have a Feed The Beast Techworld 2 Server, and I would love the idea of multiverse on it but using a high-tech solution as opposed to a few easily made obsidian blocks...

Is there an ability to control the blocks needed to make a portal?

Ultimately, it would be awesome to have a portal that required very high-end materials and tons of power to operate.  This would make this mod a end-game goal for allot of high-tech servers who have excessive power (from reactors) that they have no use for!

Regardless this is an amazing mod, and I have used older versions but would love a higher tech portal solution if possible!

**Comment by FernFerret** [comment]
The portal framework as it's written today does not support this since we don't care what blocks portals are made of in the code. Unfortunately this is a bit too large and specific of a task that I'm going to say that this doesn't fit in the MultiversePortals scope. I'm sure someone could make it, but the portals would be more specific.

Best of luck!
