### ISSUE TITLE
help while creating proals with the dest

### ISSUE THREAD

**Issue by dukeboyty** [Multiverse/Multiverse-Portals#341]
when i create a portal and then another one then do the mvp modify dest p:{test} then do the other one and then i do mvp select and then mvp modify dest p:{test2}and it names the test2 test and it will work from the first one {test} it works and then i try to go throw {test2} it does not work. on portal {test2 i do mvp select and then it says portal {test} and it keeps doing it i have tryed deleting and re-downloading it but it still does not work sorry about the dis it was hard to dis crab it it is eraser to say.

PLS HELP

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
