### ISSUE TITLE
Price entry fee not work

### ISSUE THREAD

**Issue by ULiX80** [Multiverse/Multiverse-Portals#342]
Set price on portal.
Does not require a fee. Does not remove the charge.

Set price on world and...
Portal required fee but after teleport entryfee not remove and add to account player!!!!

Receive message:
[Multierse-Core] 10.0 GOLD_INGOT has been added to your account.

"Addeded"!!! :)

Teleport cost 10 Gold Ingot and instead of subtracting the board obtain multiplication!

**Comment by dumptruckman** [comment]
Is this still occurring in the latest dev builds?

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
