### ISSUE TITLE
Players get disconnected when changing world!!

### ISSUE THREAD

**Issue by EdwardGandT** [Multiverse/Multiverse-Portals#344]
Hi there! My name is EdwardGandT, and I need your help! I am using multiverse and Multiverse-Portals but everytime I switch worlds everyone gets disconnected. 
Ex: I am at world 1, and when I switch to world 2 all players get disconnected. (and with other players to, I get disconnected as well)

If anyone can help me I would really enjoy that!!! So can anyone help me to fix this multiverse problem?

Will be awaiting an answer,
EdwardGandT

**Comment by MinesanityPvP** [comment]
Please check in your console for any errors logged in console! Then report back :D

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
