### ISSUE TITLE
Ars Magica Serious Issue

### ISSUE THREAD

**Issue by Zsashas** [Multiverse/Multiverse-Portals#345]
So there appears to be an issue with this and Ars Magica 2 (1.7.10). Upon travelling through a portal to a Multiverse dimension, or from one back to the overworld, all Ars Magica progress is seemingly wiped. The mana and burnout bars disappear, and I am unable to look in an Occulus. Upon creating another Compendium by some Etherium, however, the UI does not return as it should. It's as if the game thinks I've already unlocked mana, therefore won't let me do it again. This is a rather serious issue. It seemingly permanently prevents any progress with AM2.

**Comment by FernFerret** [comment]
Sorry, this shouldn't have anything to do with Multiverse or Portals, I'd bet that your other mod doesn't support multiple worlds, since we just use the standard world traversal API. Now for my generic message:

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

**Comment by Zsashas** [comment]
Seems like this was probably connected to the same issue when returning from the End. Also wow this was a while ago... :P
