### ISSUE TITLE
Multiverse-portals don't teleport..

### ISSUE THREAD

**Issue by hktomiki1** [Multiverse/Multiverse-Portals#346]
Hello! OP:s and default group can teleport to kitpvp with created portal, but anyone else, but op's can teleport with any portal.  One group (Emerald-VIP) cannot teleport to kitpvp or nether with created portal.. But can teleport building map. Permissions are fine! (multiverse.portal.access.Nether1) and (multiverse.portal.access.Nether2) and multiverse.access.world_nether.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
