### ISSUE TITLE
Multiverse-Portal Doesnt Teleport Default Player

### ISSUE THREAD

**Issue by BlueAppleSC** [Multiverse/Multiverse-Portals#353]
How do i fix this ?
should i enter any permission for default player to teleport by portal ?
only op can teleport with portal , please help !

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
