### ISSUE TITLE
Please update the selection call to new WorldEdit6 API (or /mvp create will never work)

### ISSUE THREAD

**Issue by OriginalMadman** [Multiverse/Multiverse-Portals#356]
When marking and creating portals, this call always failed since it was changed in WE6 (and WE5 is not functional in spigot 1.8 - leaving us hanging):

Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;

I know its not your fault, but not sure they're re-adding legacy support for the selections.

Thanks

**Comment by Ironic8b498** [comment]
I have the same issue and from TWSSYesterday's comment I was able to create a portal manually. Since I'm running Worldedit 6.0 and have to run it for other plugins, I just copied and pasted a portal in the portals.yml file and edited with correct cords and changed portal name and destination worked great.

**Comment by bman87** [comment]
+1 for this fix.  Adding portals manually is a pain!

**Comment by Ironic8b498** [comment]
yes it is a pain, I have not been able to figure out how to manually configure a new portal.yml file. Been working on running the newest Spigot and decided to do fresh install of all plugins to see if that will clear up the issues I'm having. Well I'm not able to create a portal so I will not be able to see. I even tried to use the portla.yml file from running server, will not let portals run.
