### ISSUE TITLE
Multiverse portal wont teleport back

### ISSUE THREAD

**Issue by jasonthesurvivor** [Multiverse/Multiverse-Portals#358]
I made 2 portals, pokemon1 and pokemon2. i made the pokemon1 portal to teleport to pokemon2 portal, and then I select the pokemon2 portal and then i modify dest p:pokemon1. but it wont teleport. help me please

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
