### ISSUE TITLE
Help Teleporting

### ISSUE THREAD

**Issue by Coldercraft** [Multiverse/Multiverse-Portals#361]
I want to allow players to world2 from world1 then they can teleport back to world1 but they will arrive in the place they left!!

**Comment by FernFerret** [comment]
You should check out [OpenWarp](http://ci.onarandombox.com/view/Other%20Great%20Plugins/job/OpenWarp/) along with the [help pages for it](https://github.com/PneumatiCraft/OpenWarp/wiki).

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it. 

I'm closing this issue because it is outside the scope of what we want to do in Multiverse-Portals.
