### ISSUE TITLE
Portal leads to nether when teleported to world

### ISSUE THREAD

**Issue by Alex31782** [Multiverse/Multiverse-Portals#362]
So when i make a portal with the nether portal block portal it sends me to the world, then it sends me to the nether. Please help!!

**Comment by LavaGaming** [comment]
Are you sure they're not in creative? If they are, you may want to turn nether to false in your server.properties.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
