### ISSUE TITLE
People suffocating in Portals

### ISSUE THREAD

**Issue by whitelily36** [Multiverse/Multiverse-Portals#363]
Players are finding themselves spawning underneath the destination points when they use a portal and this sometimes results in them suffocating.  Is there anything we can do to prevent this?

**Comment by FernFerret** [comment]
What destination type are you using? Are you using exact? 

Also, here's my generic message:

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

**Comment by whitelily36** [comment]
Most of the time they are set up this way:

Select the portal and do:
/mvp create portalname

Then go to the destination, face the way you want the player to appear and
do...
/mvp modify dest here

That not the best way?
