### ISSUE TITLE
Portal Number Limit?

### ISSUE THREAD

**Issue by ChaoticMCNetwork** [Multiverse/Multiverse-Portals#383]
There seems to be some kind of limit on the number of portals that will work after creation.  I have many portals that work just fine, but the most recent ones simply don't do anything.  No error reported - just nothing.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!
