### ISSUE TITLE
ServerVersion: 1.14 | Problem: It says (You need to LEFT click on a block with your wand!)

### ISSUE THREAD

**Issue by Kieqo** [Multiverse/Multiverse-Portals#505]
DELET THIS PLEASE

**Comment by ElectricFreak** [comment]
Did you fix this?

**Comment by Jadiction** [comment]
I don't understand the issue? Can you elaborate and provide more information?

**Comment by ElectricFreak** [comment]
Haven’t tried this recently, but when I get home in a few hours I’ll try to replicate the problem again and provide more information. Thanks.

**Comment by ElijahPepe** [comment]
What do you mean no information? The issue was explained, the wand doesn't do anything.

**Comment by EbonJaeger** [comment]
The issue may have been explained once, but it sure isn't now. So no, there is no information.

**Comment by Jadiction** [comment]
@ElijahPepe Simply putting the title as the error message doesn't give enough information at all, especially if there is an actual bug and a fix is needed. So no, the issue was NOT explained. Considering I have yet to encounter this issue and have never heard about it, I'd need much more information to replicate it and report it to the developer(s). What MV (core and portal) versions? Are you using WorldEdit's wand or Multiverse's wand? What's the config look like? (Is the wand item changed?) It could also be a plugin conflict. Try to load multiverse itself and see if the problem persists, if not, then it's not on Multiverse.

**Comment by Jadiction** [comment]
Closing ticket due to lack of information. Please open a new ticket with more valid information if this issue is still occurring in the latest versions or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
