### ISSUE TITLE
Players cant acceess

### ISSUE THREAD

**Issue by tetraboy2011** [Multiverse/Multiverse-Portals#94]
I have portals in a world but on ops can go through i did the •Multiverse Portals Permissions

/mv conf enforceaccess false

/mvp conf enforceportalaccess false

commands but it still doesnt work. please help me.
thanks,
Andrew

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
